//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 12:36:25 AM EEST 
//


package com.tourist_trips;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;



/**
 * <p>Java class for CruiseTrip complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CruiseTrip">
 *   &lt;complexContent>
 *     &lt;extension base="{}Trip">
 *       &lt;sequence>
 *         &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CabinType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfPortsVisited" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CruiseTrip", propOrder = {
    "shipName",
    "cabinType",
    "numberOfPortsVisited"
})
public class CruiseTrip
    extends Trip
{

    @XmlElement(name = "ShipName", required = true)
    protected String shipName;
    @XmlElement(name = "CabinType", required = true)
    protected String cabinType;
    @XmlElement(name = "NumberOfPortsVisited")
    protected int numberOfPortsVisited;

    /**
     * Gets the value of the shipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipName() {
        return shipName;
    }

    /**
     * Sets the value of the shipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipName(String value) {
        this.shipName = value;
    }

    /**
     * Gets the value of the cabinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCabinType() {
        return cabinType;
    }

    /**
     * Sets the value of the cabinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCabinType(String value) {
        this.cabinType = value;
    }

    /**
     * Gets the value of the numberOfPortsVisited property.
     * 
     */
    public int getNumberOfPortsVisited() {
        return numberOfPortsVisited;
    }

    /**
     * Sets the value of the numberOfPortsVisited property.
     * 
     */
    public void setNumberOfPortsVisited(int value) {
        this.numberOfPortsVisited = value;
    }

}
