//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 12:36:25 AM EEST 
//


package com.tourist_trips;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ExcursionTrip complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcursionTrip">
 *   &lt;complexContent>
 *     &lt;extension base="{}Trip">
 *       &lt;sequence>
 *         &lt;element name="GuideIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ExcursionDuration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LandmarksCovered" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcursionTrip", propOrder = {
    "guideIncluded",
    "excursionDuration",
    "landmarksCovered"
})
public class ExcursionTrip
    extends Trip
{

    @XmlElement(name = "GuideIncluded")
    protected boolean guideIncluded;
    @XmlElement(name = "ExcursionDuration")
    protected int excursionDuration;
    @XmlElement(name = "LandmarksCovered", required = true)
    protected List<String> landmarksCovered;

    /**
     * Gets the value of the guideIncluded property.
     * 
     */
    public boolean isGuideIncluded() {
        return guideIncluded;
    }

    /**
     * Sets the value of the guideIncluded property.
     * 
     */
    public void setGuideIncluded(boolean value) {
        this.guideIncluded = value;
    }

    /**
     * Gets the value of the excursionDuration property.
     * 
     */
    public int getExcursionDuration() {
        return excursionDuration;
    }

    /**
     * Sets the value of the excursionDuration property.
     * 
     */
    public void setExcursionDuration(int value) {
        this.excursionDuration = value;
    }

    /**
     * Gets the value of the landmarksCovered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the landmarksCovered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLandmarksCovered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLandmarksCovered() {
        if (landmarksCovered == null) {
            landmarksCovered = new ArrayList<String>();
        }
        return this.landmarksCovered;
    }

}
