//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.21 at 07:07:27 PM EEST 
//


package com.tourist_trips;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tourist_trips package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tourist_trips
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Trips }
     * 
     */
    public Trips createTrips() {
        return new Trips();
    }

    /**
     * Create an instance of {@link Trips.Trip }
     * 
     */
    public Trips.Trip createTripsTrip() {
        return new Trips.Trip();
    }

    /**
     * Create an instance of {@link ExcursionTrip }
     * 
     */
    public ExcursionTrip createExcursionTrip() {
        return new ExcursionTrip();
    }

    /**
     * Create an instance of {@link com.tourist_trips.Trip }
     * 
     */
    public com.tourist_trips.Trip createTrip() {
        return new com.tourist_trips.Trip();
    }

    /**
     * Create an instance of {@link VacationTrip }
     * 
     */
    public VacationTrip createVacationTrip() {
        return new VacationTrip();
    }

    /**
     * Create an instance of {@link TreatmentTrip }
     * 
     */
    public TreatmentTrip createTreatmentTrip() {
        return new TreatmentTrip();
    }

    /**
     * Create an instance of {@link CruiseTrip }
     * 
     */
    public CruiseTrip createCruiseTrip() {
        return new CruiseTrip();
    }

    /**
     * Create an instance of {@link ShoppingTrip }
     * 
     */
    public ShoppingTrip createShoppingTrip() {
        return new ShoppingTrip();
    }

}
