//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 12:36:25 AM EEST 
//


package com.tourist_trips;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShoppingTrip complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShoppingTrip">
 *   &lt;complexContent>
 *     &lt;extension base="{}Trip">
 *       &lt;sequence>
 *         &lt;element name="ShoppingCenter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiscountsAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="NumberOfShops" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShoppingTrip", propOrder = {
    "shoppingCenter",
    "discountsAvailable",
    "numberOfShops"
})
public class ShoppingTrip
    extends Trip
{

    @XmlElement(name = "ShoppingCenter", required = true)
    protected String shoppingCenter;
    @XmlElement(name = "DiscountsAvailable")
    protected boolean discountsAvailable;
    @XmlElement(name = "NumberOfShops")
    protected int numberOfShops;

    /**
     * Gets the value of the shoppingCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShoppingCenter() {
        return shoppingCenter;
    }

    /**
     * Sets the value of the shoppingCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShoppingCenter(String value) {
        this.shoppingCenter = value;
    }

    /**
     * Gets the value of the discountsAvailable property.
     * 
     */
    public boolean isDiscountsAvailable() {
        return discountsAvailable;
    }

    /**
     * Sets the value of the discountsAvailable property.
     * 
     */
    public void setDiscountsAvailable(boolean value) {
        this.discountsAvailable = value;
    }

    /**
     * Gets the value of the numberOfShops property.
     * 
     */
    public int getNumberOfShops() {
        return numberOfShops;
    }

    /**
     * Sets the value of the numberOfShops property.
     * 
     */
    public void setNumberOfShops(int value) {
        this.numberOfShops = value;
    }
    @Override
    public String toString() {
        return super.toString() +
                ", Shopping Center: " + shoppingCenter +
                ", Discounts Available: " + discountsAvailable +
                ", Number of Shops: " + numberOfShops;
    }
    @Override
    public String getTripType() {
        return "Shopping Trip";
    }
}
