//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 12:36:25 AM EEST 
//


package com.tourist_trips;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Trip" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Vacation" type="{}VacationTrip"/>
 *                   &lt;element name="Excursion" type="{}ExcursionTrip"/>
 *                   &lt;element name="Treatment" type="{}TreatmentTrip"/>
 *                   &lt;element name="Shopping" type="{}ShoppingTrip"/>
 *                   &lt;element name="Cruise" type="{}CruiseTrip"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trip"
})
@XmlRootElement(name = "Trips")
public class Trips {

    @XmlElement(name = "Trip", required = true)
    protected List<Trips.Trip> trip;

    /**
     * Gets the value of the trip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trips.Trip }
     * 
     * 
     */
    public List<Trips.Trip> getTrip() {
        if (trip == null) {
            trip = new ArrayList<Trips.Trip>();
        }
        return this.trip;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Vacation" type="{}VacationTrip"/>
     *         &lt;element name="Excursion" type="{}ExcursionTrip"/>
     *         &lt;element name="Treatment" type="{}TreatmentTrip"/>
     *         &lt;element name="Shopping" type="{}ShoppingTrip"/>
     *         &lt;element name="Cruise" type="{}CruiseTrip"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vacation",
        "excursion",
        "treatment",
        "shopping",
        "cruise"
    })
    public static class Trip {

        @XmlElement(name = "Vacation")
        protected VacationTrip vacation;
        @XmlElement(name = "Excursion")
        protected ExcursionTrip excursion;
        @XmlElement(name = "Treatment")
        protected TreatmentTrip treatment;
        @XmlElement(name = "Shopping")
        protected ShoppingTrip shopping;
        @XmlElement(name = "Cruise")
        protected CruiseTrip cruise;

        /**
         * Gets the value of the vacation property.
         * 
         * @return
         *     possible object is
         *     {@link VacationTrip }
         *     
         */
        public VacationTrip getVacation() {
            return vacation;
        }

        /**
         * Sets the value of the vacation property.
         * 
         * @param value
         *     allowed object is
         *     {@link VacationTrip }
         *     
         */
        public void setVacation(VacationTrip value) {
            this.vacation = value;
        }

        /**
         * Gets the value of the excursion property.
         * 
         * @return
         *     possible object is
         *     {@link ExcursionTrip }
         *     
         */
        public ExcursionTrip getExcursion() {
            return excursion;
        }

        /**
         * Sets the value of the excursion property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExcursionTrip }
         *     
         */
        public void setExcursion(ExcursionTrip value) {
            this.excursion = value;
        }

        /**
         * Gets the value of the treatment property.
         * 
         * @return
         *     possible object is
         *     {@link TreatmentTrip }
         *     
         */
        public TreatmentTrip getTreatment() {
            return treatment;
        }

        /**
         * Sets the value of the treatment property.
         * 
         * @param value
         *     allowed object is
         *     {@link TreatmentTrip }
         *     
         */
        public void setTreatment(TreatmentTrip value) {
            this.treatment = value;
        }

        /**
         * Gets the value of the shopping property.
         * 
         * @return
         *     possible object is
         *     {@link ShoppingTrip }
         *     
         */
        public ShoppingTrip getShopping() {
            return shopping;
        }

        /**
         * Sets the value of the shopping property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShoppingTrip }
         *     
         */
        public void setShopping(ShoppingTrip value) {
            this.shopping = value;
        }

        /**
         * Gets the value of the cruise property.
         * 
         * @return
         *     possible object is
         *     {@link CruiseTrip }
         *     
         */
        public CruiseTrip getCruise() {
            return cruise;
        }

        /**
         * Sets the value of the cruise property.
         * 
         * @param value
         *     allowed object is
         *     {@link CruiseTrip }
         *     
         */
        public void setCruise(CruiseTrip value) {
            this.cruise = value;
        }

    }

}
